# Generated by Django 5.0 on 2023-12-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('Cliente', 'Cliente'), ('Funcionario', 'Funcionario')], max_length=20)),
            ],
        ),
    ]
